run_name: llama-sft
base_model: "unsloth/llama-3-8b"
dataset_path: "data/raw/dataset.json"
output_dir: "models/llama-sft"
batch_size: 2
grad_accum: 4
learning_rate: 2.0e-4
max_steps: 60
warmup_steps: 5
max_seq_length: 2048
lora_r: 16
lora_alpha: 16
target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
random_state: 3407
