name: Pylint

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/**

concurrency:
  # cancel any running action on new push
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # lint:
  #   name: Code Linting (Pylint + Ruff + Black)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.10"

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -e ".[dev]"

  #     - name: Run Pylint
  #       run: pylint $(git ls-files '*.py')

  #     - name: Run Black check (code formatting)
  #       run: black --check src/ tests/

  #     - name: Run Ruff (linter + autofix checker)
  #       run: ruff check src/ tests/

  # test:
  #   name: Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.10"

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -e ".[dev]"

  #     - name: Run tests with coverage
  #       run: |
  #         pytest --cov=src --cov-report=term-missing

  # typecheck:
  #   name: Static Type Checking (mypy)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.10"

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -e ".[dev]"

  #     - name: Run mypy
  #       run: mypy src/ tests/

  license-audit:
    name: Dependency License Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install project and pip-licenses
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pip-licenses

      - name: Run license check
        run: |
          pip-licenses \
          --allow-only="MIT;MIT OR X11;BSD;ISC;Apache-2.0;Python-2.0;Unlicense;CC0-1.0;MPL-2.0;BlueOak-1.0.0;CC-BY-3.0;CC-BY-4.0;LGPL-3.0-or-later" \
          --format=markdown
